[project]
name = "keyvaluemapping"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "inquirer>=3.4.0",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
]
